var curTab,intrvl=0,aeCalled=!1;if(document.addEventListener)document.addEventListener("DOMContentLoaded",Init);else if(document.attachEvent){var TryScroll=function(){if(!aeCalled)try{document.documentElement.doScroll("left"),aeCalled=!0,Init()}catch(a){setTimeout(TryScroll,10)}};TryScroll()}else window.onload=Init;window.onpopstate=function(a){a.state&&LoadCanvas(document.getElementById(a.state.id))};
function Init(){SetXURL(document);SetXHRef(document);var a=GetHashID(),e=GetURLID();a?(curTab=document.getElementById("wcode"),LoadCanvas(document.getElementById(a))):curTab=e?document.getElementById(e):document.getElementById("wcode");!a&&!e&&window.history.replaceState({id:"wcode"},"","/");return!1}function GetURLID(){var a=window.location.pathname;return"/"==a?"":a.substring(1)}function GetHashID(){var a=window.location.hash;return 0==a.length?"":a.substring(2)}
function SetXURL(a){a=getElementsByClassName(a,"XURL");var e=a.length;for(i=0;i<e;i++)a[i].children[0].onclick=function(){return!1},a[i].onclick=LoadCanvasI}function SetXHRef(a){a=getElementsByClassName(a,"XHRef");var e=a.length;for(i=0;i<e;i++)a[i].onclick=LoadCanvasL}function LoadCanvasI(){LoadCanvasH(this);return!1}function LoadCanvasL(){var a=this.getAttribute("data-xhref");LoadCanvasH(document.getElementById(a));return!1}
function LoadCanvasH(a){URLid="wcode"==a.id?"":a.id;LoadCanvas(a);window.history.pushState({id:a.id},"","/"+URLid);"undefined"!==typeof _gaq&&_gaq.push(["_trackPageview"],"/"+URLid)}
function LoadCanvas(a){curTab&&curTab.classList.remove("sidebar-nav-high");curTab=a;a.classList.add("sidebar-nav-high");var e=document.getElementById("sidebar-nav");e.style.display="none";e.style.display="block";e=document.getElementById("updated");document.getElementById("canvas-main").innerHTML="";e.style.display="none";BeginLoading();var j=new XMLHttpRequest,j=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");j.onreadystatechange=function(){if(4==j.readyState){var g=
document.getElementById("updated"),e=document.getElementById("date"),l=document.getElementById("canvas-main");switch(j.status){case 200:KillLoading();var m=j.responseText,h=m.slice(0,1),b=m.slice(1,2);e.innerHTML=m.slice(2,13);g.style.display="block";g="WCode";"wcode"!=a.id&&(g+=" - "+a.innerText);e=Number(m.slice(13,16));0!=e&&(g+=" : "+m.slice(16,16+e));document.title=g;l.innerHTML=m.slice(16+e);"1"==h&&SetXHRef(document);"1"==b&&eval(a.id+"()");break;case 404:e.innerHTML="";g.style.display="none";
l.innerHTML="Error: 404 - Resource not found!";break;case 408:case 501:case 502:e.innerHTML="",g.style.display="none",l.innerHTML="Error!"}}};j.open("GET",a.id+".html",!0);j.setRequestHeader("Content-Type","text/plain;charset=UTF-8");j.send()}function Loading(){var a=document.getElementById("loading");void 0===Loading.count?(Loading.count=0,a.innerText="Loading",a.setAttribute("style","display: block")):3==Loading.count?KillLoading():(a.innerText+=".",Loading.count++)}
function BeginLoading(){clearTimeout(intrvl);intrvl=setInterval(Loading,1E3)}function KillLoading(){var a=document.getElementById("loading");Loading.count=void 0;a.setAttribute("style","display: none");clearTimeout(intrvl)}function about_me(){gapi.plus.go("me_g-plus");twttr.widgets.load()}function presentation(){BeginLoading()}
function getElementsByClassName(a,e){if(a.getElementsByClassName)return a.getElementsByClassName(e);var j=a;null==j&&(j=document);var g=[],j=j.getElementsByTagName("*"),u=j.length,l=RegExp("(^|\\s)"+e+"(\\s|$)"),m,h;for(h=m=0;m<u;m++)l.test(j[m].className)&&(g[h]=j[m],h++);return g}
"undefined"!==typeof document&&!("classList"in document.createElement("a"))&&function(a){a=(a.HTMLElement||a.Element).prototype;var e=Object,j=String.prototype.trim||function(){return this.replace(/^\s+|\s+$/g,"")},g=Array.prototype.indexOf||function(a){for(var b=0,e=this.length;b<e;b++)if(b in this&&this[b]===a)return b;return-1},u=function(a,b){this.name=a;this.code=DOMException[a];this.message=b},l=function(a,b){if(""===b)throw new u("SYNTAX_ERR","An invalid or illegal string was specified");if(/\s/.test(b))throw new u("INVALID_CHARACTER_ERR",
"String contains an invalid character");return g.call(a,b)},m=function(a){for(var b=j.call(a.className),b=b?b.split(/\s+/):[],e=0,g=b.length;e<g;e++)this.push(b[e]);this._updateClassName=function(){a.className=this.toString()}},h=m.prototype=[],b=function(){return new m(this)};u.prototype=Error.prototype;h.item=function(a){return this[a]||null};h.contains=function(a){return-1!==l(this,a+"")};h.add=function(a){a+="";-1===l(this,a)&&(this.push(a),this._updateClassName())};h.remove=function(a){a=l(this,
a+"");-1!==a&&(this.splice(a,1),this._updateClassName())};h.toggle=function(a){a+="";-1===l(this,a)?this.add(a):this.remove(a)};h.toString=function(){return this.join(" ")};if(e.defineProperty){h={get:b,enumerable:!0,configurable:!0};try{e.defineProperty(a,"classList",h)}catch(q){-2146823252===q.number&&(h.enumerable=!1,e.defineProperty(a,"classList",h))}}else e.prototype.__defineGetter__&&a.__defineGetter__("classList",b)}(self);
(!window.history||!window.history.pushState)&&function(a,e,j,g,u){var l=a.document,m=l.documentElement,h=a.history||{},b=a.location,q=!!h.pushState,Y=q&&h.state===u,w=b.href,v=a.JSON||{},A=Object.defineProperty,B=Object.prototype.__defineGetter__,Z=Object.prototype.__defineSetter__,U=h.pushState,V=h.replaceState,G=a.sessionStorage,C=Object.prototype.hasOwnProperty,$=Object.prototype.toString,H=+((a.eval&&eval("/*@cc_on 1;@*/")&&/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0),aa=(new Date).getTime(),
x=(A||B)&&(!H||8<H)?0:1,p=8>H?l.createElement("iframe"):j,y,D,E,F="",I=(y="addEventListener",a[y])||(y="attachEvent",F="on",a[y]),ba=(D="removeEventListener",a[D])||(D="detachEvent",a[D]),ca=(E="dispatchEvent",a[E])||(E="fireEvent",a[E]),J=[],W=[],N=0,z={onpopstate:J,popstate:J,onhashchange:W,hashchange:W},t=function(){var a,d,b,f={basepath:"/",redirect:0,type:"/"};b=l.getElementsByTagName("SCRIPT");for(a=0;b[a];a++)if(d=/(.*)\/(?:history|spike)(?:-\d\.\d(?:\.\d)?\w?)?(?:\.min)?.js\?(.*)$/i.exec(b[a].src)||
a===b.length-1&&2===(d=b[a].src.split("?")).length&&(d[2]=d[1])&&d){a=0;for(b=d[2].split("&");b[a];)d=b[a++].split("="),f[d[0]]="true"==d[1]?e:"false"==d[1]?j:d[1]||"";f.basepath=f.basepath||"/";break}return f}(),n=function(a){var d,e,f,c,j,k,g,ea=RegExp("^"+t.basepath,"i");return function(r,fa){if(r){if(!q||H){var h=n(),l=h._pathname,m=h._protocol;r=/^(?:[\w0-9]+\:)?\/\//.test(r)?0===r.indexOf("/")?m+r:r:m+"//"+h._host+(0===r.indexOf("/")?r:0===r.indexOf("?")?l+r:0===r.indexOf("#")?l+h._search+r:
l.replace(/[^\/]+$/g,"")+r)}}else if(r=b.href,!q||fa)r=b.protocol+"//"+b.host+t.basepath+(r.replace(/^[^#]*/,"")||"#").replace(RegExp("^#[/]?(?:"+t.type+")?"),"");if(d!==r){a.href=d=r;k=a.port;j=a.host;g=a.pathname;if("http:"===a.protocol&&80==k||"https:"===a.protocol&&443==k)j=a.hostname,k="";g=0===g.indexOf("/")?g:"/"+g;e=g+a.search+a.hash;c=g.replace(ea,t.type)+a.search;f=c+a.hash}return{_href:a.protocol+"//"+j+e,_protocol:a.protocol,_host:j,_hostname:a.hostname||b.hostname,_port:k||b.port,_pathname:g,
_search:a.search,_hash:a.hash,_relative:e,_nohash:c,_special:f}}}(l.createElement("a")),s=!x?h:{back:h.back,forward:h.forward,go:h.go,pushState:g,replaceState:g,emulate:!q,toString:function(){return"[object History]"}},K={state:{get:function(){return p&&p.storage||Q()[s.location.href]||g}},length:{get:function(){return h.length}},location:{set:function(da){a.location=da},get:function(){return q?b:R}}},R={assign:function(a){b.assign(q||0!==a.indexOf("#")?a:"#"+n()._nohash+a)},reload:b.reload,replace:function(a){b.replace(q||
0!==a.indexOf("#")?a:"#"+n()._nohash+a)},toString:function(){return this.href}},ga={href:{set:function(a){b.href=a},get:function(){return n()._href}},protocol:{set:function(a){b.protocol=a},get:function(){return b.protocol}},host:{set:function(a){b.host=a},get:function(){return b.host}},hostname:{set:function(a){b.hostname=a},get:function(){return b.hostname}},port:{set:function(a){b.port=a},get:function(){return b.port}},pathname:{set:function(a){b.pathname=a},get:function(){return n()._pathname}},
search:{set:function(a){b.search=a},get:function(){return n()._search}},hash:{set:function(a){a=0===a.indexOf("#")?a:"#"+a;var d=n();p?a!=d._hash&&(s.pushState(g,g,d._nohash+a),X({oldURL:d._href})):b.hash="#"+d._nohash+a},get:function(){return n()._hash}}},S=function(b,d,g){var f=b,c,h=j;if(A||B)for(c in d){if(C.call(d,c))if(B)d[c].get&&B.call(b,c,d[c].get),d[c].set&&Z.call(b,c,d[c].set);else if(A)try{A(b,c,d[c])}catch(k){if(g)return j;h=e;break}}else h=e;if(h&&x){g="StaticClass"+aa+x++;f=["Class "+
g];"execVB"in a||execScript("Function execVB(c) ExecuteGlobal(c) End Function","VBScript");"VBCVal"in a||execScript("Function VBCVal(o,r) If IsObject(o) Then Set r=o Else r=o End If End Function","VBScript");for(c in b)f[f.length]="Public ["+c+"]";C.call(b,"toString")&&(b.propertyIsEnumerable("toString")||(f[f.length]="Public [toString]"),d["(toString)"]={get:function(){return this.toString.call(this)}});for(c in d)C.call(d,c)&&(d[c].get&&(b["get "+c]=d[c].get,f.push("Public [get "+c+"]","Public "+
("(toString)"===c?"Default ":"")+"Property Get ["+c+"]","Call VBCVal(me.[get "+c+"].call(me),["+c+"])","End Property")),d[c].set&&(b["set "+c]=d[c].set,f.push("Public [set "+c+"]","Public Property Let ["+c+"](v)","Call me.[set "+c+"].call(me,v)","End Property","Public Property Set ["+c+"](v)","Call me.[set "+c+"].call(me,v)","End Property")));f.push("End Class","Function "+g+"Factory()","Set "+g+"Factory=New "+g,"End Function");execVB(f.join("\n"));f=a[g+"Factory"]();for(c in b)f[c]=b[c];C.call(b,
"toString")&&(f.toString=b.toString)}return f},L=v.stringify||function(a){function b(a){var c=/[\\\"\u0000-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};c.lastIndex=0;return c.test(a)?'"'+a.replace(c,function(a){var b=d[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}var g=function(f){var c,e,k;
c=(typeof f).charCodeAt(2);if(114===c)f=b(f);else if(109===c)f=isFinite(f)?String(f):"null";else if(111===c||108===c)f=String(f);else if(106===c)if(f){e=(c="[object Array]"===$.apply(f))?"[":"{";if(c)for(k=0;k<f.length;k++)e+=(0==k?"":",")+g(f[k]);else for(k in f)C.call(f,k)&&f[k]!==a&&(e+=(1==e.length?"":",")+b(k)+":"+g(f[k]));f=e+(c?"]":"}")}else f="null";else f=a;return f};return g}(),T=function(){var a=v.parse;return function(b){return b?a?a(b):(new Function("return "+b))():g}}(),Q=function(a){return G?
a?G.setItem("__hitoryapi__",L(a)):T(G.getItem("__hitoryapi__"))||{}:{}},M=function(b,d,e){var f=2===b?a.onhashchange:a.onpopstate,c=2===b?"hashchange":"popstate",g=z[c];l.createEvent?(b=l.createEvent("Events"),b.initEvent(c,j,j)):(b=l.createEventObject(),b.type=c);b.state=s.state;b.oldURL=d;b.newURL=e;f&&f.call(a,b);d=0;for(e=g.length;d<e;d++)g[d].call(a,b)},X=function(){var p=a.onpopstate||g,d=a.onhashchange||g,O=0,f=g,c=n(),P=c._href;c._hash.replace(/^#/,"");var k=function(){if(w&&!(w=0)&&c._relative!==
t.basepath)clearInterval(f),setTimeout(M,10)},v=function(a){var b=n();if(N)return P=b._href,N=0;var c=a.oldURL||P;a=P=a.newURL||b._href;var b=c.replace(/^.*?(#|$)/,""),e=a.replace(/^.*?(#|$)/,"");c!=a&&!O&&M();w=O=0;b!=e&&M(2,c,a)};I(F+"hashchange",v,j);I(F+"popstate",function(){if(w===b.href)return w=0;w=0;M(O=1)},j);s.redirect=function(c,d){t.type=c===u?t.type:c;t.basepath=d===u?t.basepath:d;if(a.top==a.self){var f=n(g,e)._relative,k=b.search,h=b.pathname;d=t.basepath;q?(f!=d&&RegExp("^"+d+"$",
"i").test(h)&&(b.href=f),RegExp("^"+d+"$","i").test(h+"/")?b.href=d:RegExp("^"+d,"i").test(h)||(b.href=h.replace(/^\//,d)+k)):h!=d&&(b.href=d+"#"+h.replace(RegExp("^"+d,"i"),t.type)+k+b.hash)}};s=S(s,x?K:h.state===u?{state:K.state,location:K.location}:{location:K.location});R=S(R,ga);a[y]=function(a,b,c,d){z[a]?(z[a].push(b),!q&&J===z[a]&&k()):I(a,b,c,d)};a[D]=function(a,b,c){var d=z[a];if(d)for(a=d.length;--a;){if(d[a]===b){d.splice(a,1);break}}else ba(a,b,c)};a[E]=function(b,c){var d=z[b],f=d===
J?a.onpopstate:a.onhashchange;if(d){c=c||("string"==typeof b?a.event:b);try{c&&(c.target=a)}catch(g){try{c.srcElement=a}catch(h){}}f&&f.call(a,c);for(var f=0,k=d.length;f<k;f++)d[f].call(a,c);return e}return ca(b,c)};x&&execScript("Public history, onhashchange","VBScript");if((!A&&!B||!S(a,{onhashchange:{get:function(){return d},set:function(a){d=a||g}},onpopstate:{get:function(){return p},set:function(a){(p=a||g)&&!q&&k()}}},1))&&!q)f=setInterval(function(){a.onpopstate&&k()},100);t.redirect&&s.redirect();
if(!q)l[y](F+"click",function(b){var c=b||a.event,d=c.target||c.srcElement;b="defaultPrevented"in c?c.defaultPrevented:c.returnValue===j;if(d&&("A"===d.nodeName&&!b)&&(b=n(d.getAttribute("href",2),e),b._hash&&"#"!==b._hash&&b._hash===b._href.replace(n()._href.split("#").shift(),""))){history.location.hash=b._hash;b=b._hash.replace(/^#/,"");if((d=l.getElementById(b))&&d.id===b&&"A"===d.nodeName)d=d.getBoundingClientRect(),a.scrollTo(m.scrollLeft||0,d.top+(m.scrollTop||0)-(m.clientTop||0));c.preventDefault?
c.preventDefault():c.returnValue=!1}},j);return v}();s.pushState=function(a,d,e,f){var c=Q(),h=n()._href,k=e&&n(e);w=0;e=k?k._href:h;f&&c[h]&&delete c[h];if((!q||Y)&&G&&a)c[e]=a,Q(c),a=g;U&&V?f?V.call(s,a,d,e):U.call(s,a,d,e):k&&k._relative!=n()._relative&&(N=1,f?b.replace("#"+k._special):b.hash=k._special)};s.replaceState=function(a,b,e){s.pushState(a,b,e,1)};x?(a.history=s,function(e,d){if(p){var g,f,c=function(){var a=n()._href;d!=a&&X({oldURL:d,newURL:d=a})};f=setInterval(c,100);p.src="javascript:true;";
p=m.firstChild.appendChild(p).contentWindow;s.pushState=g=function(a,e,h,j,l){var m=p.document,q=["<script>","lfirst=1;",,"storage="+L(a)+";","\x3c/script>"];if(h=h&&n(h)){l||clearInterval(f);if(j)p.lfirst?(history.back(),g(a,e,h._href,0,1)):(p.storage=a,b.replace("#"+h._special));else if(h._href!=d||l)p.lfirst||(p.lfirst=1,g(p.storage,e,d,0,1)),q[2]='parent.location.hash="'+h._special.replace(/"/g,'\\"')+'";',m.open(),m.write(q.join("")),m.close();l||(d=n()._href,f=setInterval(c,100))}else p.storage=
a};I(F+"unload",function(){if(p.storage){var a={};a[n()._href]=p.storage;l.cookie="_historyAPI="+escape(L(a))}clearInterval(f)},j);if(1<e.length){e=unescape(e.pop().split(";").shift());try{p.storage=T(e)[n()._href]}catch(h){}}!v.parse&&!v.stringify&&(v.parse=T,v.stringify=L,a.JSON=v)}}(l.cookie.split("_historyAPI="),n()._href)):a.history.emulate=!q}(window,!0,!1,null);
